development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ArcticIndexClone_development
  pool: 5
  username: root
  password: liman2
  socket: /var/run/mysqld/mysqld.sock


test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ArcticIndexClone_test
  pool: 5
  username: root
  password: liman2
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ArcticIndexClone_production
  pool: 5
  username: root
  password: liman2
  socket: /var/run/mysqld/mysqld.sock

#production:
#  adapter: sqlite3
#  database: db/production.sqlite3
#  pool: 5
#  timeout: 5000
